from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
        migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('goal',models.CharField(default='UPSC CSE',max_length=120)),('daily_new_limit',models.PositiveIntegerField(default=20)),('daily_review_limit',models.PositiveIntegerField(default=100)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,to='auth.user'))]),
        migrations.CreateModel(name='Topic',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('subject',models.CharField(max_length=80)),('name',models.CharField(max_length=200)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='topics',to='auth.user'))],options={'unique_together':{('user','subject','name')}}),
        migrations.CreateModel(name='Source',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=300)),('file_name',models.CharField(blank=True,max_length=300)),('source_type',models.CharField(default='notes',max_length=30)),('text',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('topic',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='sources',to='core.topic')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sources',to='auth.user'))]),
        migrations.CreateModel(name='Card',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('card_type',models.CharField(choices=[('basic','Basic Recall'),('cloze','Cloze'),('reverse','Reverse'),('compare','Compare'),('sequence','Sequence'),('multi','Multi-point'),('pyq','PYQ Recall'),('mains','Mains Recall')],default='basic',max_length=20)),('prompt',models.TextField()),('answer',models.TextField()),('line_start',models.PositiveIntegerField(blank=True,null=True)),('line_end',models.PositiveIntegerField(blank=True,null=True)),('excerpt',models.TextField(blank=True)),('state',models.CharField(choices=[('new','New'),('learning','Learning'),('review','Review'),('relearning','Relearning')],default='new',max_length=20)),('learning_step',models.PositiveIntegerField(default=0)),('interval_days',models.FloatField(default=0)),('due_at',models.DateTimeField(default=django.utils.timezone.now)),('reps',models.PositiveIntegerField(default=0)),('lapses',models.PositiveIntegerField(default=0)),('ease',models.FloatField(default=2.5)),('last_reviewed',models.DateTimeField(blank=True,null=True)),('last_rating',models.CharField(blank=True,max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('source',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='cards',to='core.source')),('topic',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='cards',to='core.topic')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='cards',to='auth.user'))]),
        migrations.CreateModel(name='ReviewLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('rating',models.CharField(max_length=10)),('from_state',models.CharField(max_length=20)),('to_state',models.CharField(max_length=20)),('response_ms',models.PositiveIntegerField(default=0)),('scheduled_at',models.DateTimeField()),('created_at',models.DateTimeField(auto_now_add=True)),('card',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='reviews',to='core.card')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='reviews',to='auth.user'))]),
        migrations.CreateModel(name='PYQ',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('year',models.PositiveIntegerField()),('exam',models.CharField(default='UPSC CSE',max_length=50)),('paper',models.CharField(default='Prelims',max_length=50)),('question',models.TextField()),('answer',models.TextField(blank=True)),('subject',models.CharField(max_length=80)),('topic',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.topic')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='pyqs',to='auth.user'))]),
        migrations.CreateModel(name='MainsSubmission',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('question',models.TextField()),('answer',models.TextField()),('marks',models.FloatField(default=0)),('max_marks',models.PositiveIntegerField(default=10)),('evaluation',models.JSONField(default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='mains_submissions',to='auth.user'))]),
        migrations.CreateModel(name='MemoryItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('item_type',models.CharField(choices=[('intro','Introduction'),('example','Example'),('case','Case/Committee'),('keyword','Keyword'),('conclusion','Conclusion')],default='keyword',max_length=20)),('text',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('source_submission',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.mainssubmission')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='memory_items',to='auth.user'))]),
        migrations.CreateModel(name='KnowledgePoint',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=300)),('body',models.TextField(blank=True)),('source',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.source')),('topic',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='knowledge_points',to='core.topic')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='knowledge_points',to='auth.user'))]),
    ]
